version: '3.8'
services:
  postgres-db:
    image: postgres:16
    container_name: movie_chat_db
    environment:
      - POSTGRES_DB=moviedb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"